### ISSUE TITLE
This project could use a Discord server

### ISSUE THREAD

**Issue by gulagkulak** [Stand-Motor-Company/Project-OSAKI#5]
I'm interested in contributing to the 3D design, but a complete design would require separate components for the chassis, suspension, breaking system, etc. For the price to remain cheap, manufacturability would also have to be taken into account.

Having a Discord server would make it easier to iterate on the design by getting quick feedback on the individual components and sharing reference photos of existing off-the-shelf components like the internal suspension and breaking system so they could be modeled correctly into the 3D design.

**Comment by Stand-Motor-Company** [comment]
Welcome in :)

We've been live for some time now

https://discord.gg/YHX6CXEp3A
